In [1]:
# Import Library
import tensorflow as tf

# Version
print(tf.version)

<module 'tensorflow_core._api.v2.version' from 'C:\\Users\\lenovo\\Anaconda3\\lib\\site-packages\\tensorflow_core\\_api\\v2\\version\\__init__.py'>


### Note
A tensor is a generalizations of vectors and matrices to potentially higher dimension. Tensorflow represents tensors as n-dimensional arrays of base data types

Tensorflow has two main components:
1. Graph (Computational Graph): Tensorflow works by building a graph of defined computations. Nothing is computed or stored in this graph. Its simply a way of defining operations that have been written.
2. Sessions allows parts of the graph to be executed/evaluated. It allocates memory and resources and handles the execution of the computations we defined

In [10]:
# Creating Variable with specific data type
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(1.321, tf.float64)
print(string)
print(number)

# Creating tensors 
# 1D-array
tensor1D = tf.Variable([1.0, 2.0], tf.float64)
tensor2D = tf.Variable([[1.0, 2.0],
                        [3.0, 4.0]], tf.float64)
# tf.rank(tensor1D)
# tf.rank(tensor2D) # output ...numpy = 2 -> the rank of the tensor
print(tensor2D.shape) # the dimension of the tensor

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.321>
(2, 2)


In [12]:
# Changing shape
# Create tensor with dimension 1x2x3 with all value equals to one
tensor1 = tf.ones((1,2,3)) 
tensor2 = tf.reshape(tensor1, (2,3,1))
tensor3 = tf.reshape(tensor1, (3, -1))

print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Note
Type of tensors:
1. Variable
2. Constant
3. Placeholder
4. SparseTensor

Sometimes the tensor is a product of operations of tensors, those tensor created as a computational graph, To evaluate the value of the tensor we need to use tf.Session() and then calculated the value using tensor_name.eval()